name: Build documentation

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

  workflow_call:

env:
  PUBLISH_DIR: ./_build/html

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Build docs
        run: 	jupyter book build -W .
   
      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: error